export const initialState = {
  flyoutIsOpen: false,
  modal: {
    isOpen: false,
    type: "",
  },
  snackbar: {
    isOpen: false,
    type: "",
    message: "",
  },
  postings: [
    {
      id: 0,
      title: "Game Boy Advanced SP",
      date: "2018-07-01T00:00:00.000Z",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu est volutpat, luctus mauris id, bibendum sem. Mauris ultrices diam eu metus mattis, ut sodales tellus rhoncus. Nunc eleifend rutrum tortor, sit amet mattis mi euismod ac. Mauris diam ante, tincidunt in mauris et, ullamcorper fermentum urna.",
      category: "electronics",
      condition: "good",
      quantity: 1,
      tags: ["kid friendly", "retro gaming"],
      requestedItems: [
        "DualShock4 Controller",
        "Nintendo Switch Joy-Cons",
        "Hand Sanitizer",
        "Baked Goods",
      ],
      images: [{ name: "gameboy.jpg" }],
      ownerId: "2131254",
      ownerUsername: "hulkbuster",
      postalCode: "V73P6G1",
      offerings: [],
      location: "North Vancouver, BC",
    },
    {
      id: 1,
      title: "Freshly Picked Tomatoes",
      date: "2019-08-14T00:00:00.000Z",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu est volutpat, luctus mauris id, bibendum sem. Mauris ultrices diam eu metus mattis, ut sodales tellus rhoncus. Nunc eleifend rutrum tortor, sit amet mattis mi euismod ac. Mauris diam ante, tincidunt in mauris et, ullamcorper fermentum urna.",
      category: "food drink",
      condition: "brand new",
      quantity: 1,
      tags: [
        "fresh from garden",
        "organic",
        "no pesticides",
        "heirloom tomato",
      ],
      requestedItems: ["Baked Goods", "Sourdough Starter", "Zucchini"],
      images: [{ name: "tomato.jpg" }],
      ownerId: "591024",
      ownerUsername: "shellstrop",
      postalCode: "V3L0A5",
      offerings: [],
      location: "New Westminster, BC",
    },
    {
      id: 2,
      title: "Racing Bicycle (64cm)",
      date: "2020-03-14T00:00:00.000Z",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu est volutpat, luctus mauris id, bibendum sem. Mauris ultrices diam eu metus mattis, ut sodales tellus rhoncus. Nunc eleifend rutrum tortor, sit amet mattis mi euismod ac. Mauris diam ante, tincidunt in mauris et, ullamcorper fermentum urna.",
      category: "hobbies",
      condition: "brand new",
      quantity: 1,
      tags: ["never ridden", "helmet included"],
      requestedItems: ["Baked Goods", "Sourdough Starter", "Zucchini"],
      images: [{ name: "bicycle.jpg" }],
      ownerId: "591024",
      ownerUsername: "shellstrop",
      postalCode: "V3L0A5",
      offerings: [],
      location: "New Westminster, BC",
    },
    {
      id: 3,
      title: "Puzzle (1000 Pieces)",
      date: "2020-05-19T00:00:00.000Z",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu est volutpat, luctus mauris id, bibendum sem. Mauris ultrices diam eu metus mattis, ut sodales tellus rhoncus. Nunc eleifend rutrum tortor, sit amet mattis mi euismod ac. Mauris diam ante, tincidunt in mauris et, ullamcorper fermentum urna.",
      category: "hobbies",
      condition: "like new",
      quantity: 1,
      tags: ["jigsaw puzzle", "completed once"],
      requestedItems: ["Game Boy", "Puzzle (1000 piece or more)"],
      images: [{ name: "puzzle.jpg" }],
      ownerId: "3000",
      ownerUsername: "iamironman",
      postalCode: "V5K1K2",
      offerings: [],
      location: "Vancouver, BC",
    },
    {
      id: 4,
      title: "Sourdough",
      date: "2020-06-06T00:00:00.000Z",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu est volutpat, luctus mauris id, bibendum sem. Mauris ultrices diam eu metus mattis, ut sodales tellus rhoncus. Nunc eleifend rutrum tortor, sit amet mattis mi euismod ac. Mauris diam ante, tincidunt in mauris et, ullamcorper fermentum urna.",
      category: "food drink",
      condition: "brand new",
      quantity: 1,
      tags: ["homemade bread", "sourdough"],
      requestedItems: ["Tomatoes", "Coffee", "Cookies"],
      images: [{ name: "bread.jpg" }],
      ownerId: "50192",
      ownerUsername: "fatthor",
      postalCode: "V6V1A4",
      offerings: [],
      location: "Richmond, BC",
    },
    {
      id: 5,
      title: "Sourdough + Tomatoes",
      date: "2020-06-16T00:00:00.000Z",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu est volutpat, luctus mauris id, bibendum sem. Mauris ultrices diam eu metus mattis, ut sodales tellus rhoncus. Nunc eleifend rutrum tortor, sit amet mattis mi euismod ac. Mauris diam ante, tincidunt in mauris et, ullamcorper fermentum urna.",
      category: "food drink",
      condition: "brand new",
      quantity: 1,
      tags: [
        "homemade bread",
        "sourdough",
        "freshly picked",
        "heirloom tomato",
      ],
      requestedItems: ["Coffee", "Cookies", "Toilet Paper", ""],
      images: [{ name: "bread.jpg" }, { name: "tomato.jpg" }],
      ownerId: "50192",
      ownerUsername: "fatthor",
      postalCode: "V6V1A4",
      offerings: [],
      location: "Richmond, BC",
    },
  ],
  currentUser: {
    _id: "5f03d321c8c1090b3a425982",
    userName: "shellstrop",
    postalCode: "V3L0A5",
    location: "New Westminster, BC",
  },
  itemDetail: {
    id: 5,
    title: "Sourdough + Tomatoes",
    date: "2020-06-16T00:00:00.000Z",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu est volutpat, luctus mauris id, bibendum sem. Mauris ultrices diam eu metus mattis, ut sodales tellus rhoncus. Nunc eleifend rutrum tortor, sit amet mattis mi euismod ac. Mauris diam ante, tincidunt in mauris et, ullamcorper fermentum urna.",
    category: "food drink",
    condition: "brand new",
    quantity: 1,
    tags: ["homemade bread", "sourdough", "freshly picked", "heirloom tomato"],
    requestedItems: ["Coffee", "Cookies", "Toilet Paper", ""],
    images: [{ name: "bread.jpg" }, { name: "tomato.jpg" }],
    ownerId: "50192",
    ownerUsername: "fatthor",
    postalCode: "V6V1A4",
    offerings: [],
    location: "Richmond, BC",
  },
  userDetail: {
    _id: "5f03d321c8c1090b3a425982",
    firstName: "Eleanor",
    lastName: "Shellstrop",
    userName: "shellstrop",
    postalCode: "V3L0A5",
    location: "New Westminster, BC",
    postings: [
      {
        id: 1,
        title: "Freshly Picked Tomatoes",
        date: "2019-08-14T00:00:00.000Z",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu est volutpat, luctus mauris id, bibendum sem. Mauris ultrices diam eu metus mattis, ut sodales tellus rhoncus. Nunc eleifend rutrum tortor, sit amet mattis mi euismod ac. Mauris diam ante, tincidunt in mauris et, ullamcorper fermentum urna.",
        category: "food drink",
        condition: "brand new",
        quantity: 1,
        tags: [
          "fresh from garden",
          "organic",
          "no pesticides",
          "heirloom tomato",
        ],
        requestedItems: ["Baked Goods", "Sourdough Starter", "Zucchini"],
        images: [{ name: "tomato.jpg" }],
        ownerId: "591024",
        ownerUsername: "shellstrop",
        postalCode: "V3L0A5",
        offerings: [],
        location: "New Westminster, BC",
        active: true,
      },
      {
        id: 2,
        title: "Racing Bicycle (64cm)",
        date: "2020-03-14T00:00:00.000Z",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu est volutpat, luctus mauris id, bibendum sem. Mauris ultrices diam eu metus mattis, ut sodales tellus rhoncus. Nunc eleifend rutrum tortor, sit amet mattis mi euismod ac. Mauris diam ante, tincidunt in mauris et, ullamcorper fermentum urna.",
        category: "hobbies",
        condition: "brand new",
        quantity: 1,
        tags: ["never ridden", "helmet included"],
        requestedItems: ["Baked Goods", "Sourdough Starter", "Zucchini"],
        images: [{ name: "bicycle.jpg" }],
        ownerId: "591024",
        ownerUsername: "shellstrop",
        postalCode: "V3L0A5",
        offerings: [],
        location: "New Westminster, BC",
        active: false,
      },
      {
        id: 5,
        title: "Sourdough + Tomatoes",
        date: "2020-06-16T00:00:00.000Z",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu est volutpat, luctus mauris id, bibendum sem. Mauris ultrices diam eu metus mattis, ut sodales tellus rhoncus. Nunc eleifend rutrum tortor, sit amet mattis mi euismod ac. Mauris diam ante, tincidunt in mauris et, ullamcorper fermentum urna.",
        category: "food drink",
        condition: "brand new",
        quantity: 1,
        tags: [
          "homemade bread",
          "sourdough",
          "freshly picked",
          "heirloom tomato",
        ],
        requestedItems: ["Coffee", "Cookies", "Toilet Paper", ""],
        images: [{ name: "bread.jpg" }, { name: "tomato.jpg" }],
        ownerId: "50192",
        ownerUsername: "fatthor",
        postalCode: "V6V1A4",
        offerings: [],
        location: "Richmond, BC",
        active: true,
      },
    ],
  },
};
