export const ADD_POSTING_BUTTON = "ADD_POSTING_BUTTON";
export const MAKE_OFFER_BUTTON = "MAKE_OFFER_BUTTON";
export const LOGIN_REGISTER_BUTTON = "LOGIN_REGISTER_BUTTON";
export const ADD_REVIEW_BUTTON = "ADD_REVIEW_BUTTON";