export const OFFER_MODAL = "OFFER_MODAL";
export const OFFER_DETAILS_MODAL = "OFFER_DETAILS_MODAL";
export const OFFER_SENT_DETAILS_MODAL = "OFFER_SENT_DETAILS_MODAL";
export const POSTING_MODAL = "POSTING_MODAL";
export const LOGIN_MODAL = "LOGIN_MODAL";
export const REVIEW_MODAL = "REVIEW_MODAL";
